name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Analyze, and Deploy
    runs-on: self-hosted

    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Permet une analyse complète par SonarQube

            # Install Maven on Windows
      - name: Install Maven on Windows
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip" -OutFile "maven.zip"
          Expand-Archive -Path "maven.zip" -DestinationPath "$env:USERPROFILE\maven"
          echo "MAVEN_HOME=$env:USERPROFILE\maven\apache-maven-3.8.8" >> $env:GITHUB_ENV
          echo "$env:USERPROFILE\maven\apache-maven-3.8.8\bin" >> $env:GITHUB_PATH

      # Set up JDK 17 for GitHub Actions
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Maven (only if needed on self-hosted runner)
      - name: Set up Maven
        shell: powershell
        run: |
          echo "MAVEN_HOME=$env:USERPROFILE\\maven\\apache-maven-3.8.8" >> $env:GITHUB_ENV
          echo "$env:USERPROFILE\\maven\\apache-maven-3.8.8\\bin" >> $env:GITHUB_PATH

      # Verify Java version
      - name: Verify Java version
        run: java -version

      # Build and analyze with SonarQube
      - name: Build and Analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B verify sonar:sonar -Dsonar.project.settings=sonar-project.properties

